---
- name: Setup OpenVPN server
  hosts: app
  vars:
    ansible_ssh_private_key_file: ".vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"
  vars_files:
    - ./inventories/group_vars/app.yml
  become: true
  roles:
    - openvpn