- name: Setup postgresql master
  hosts: db
  become: true
  vars:
    ansible_ssh_private_key_file: ".vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"
  vars_files:
    - ./inventories/group_vars/all.yml
  become: true
  roles:
    - postgresql

- name: Setup postgresql replica
  hosts: app
  vars:
    ansible_ssh_private_key_file: ".vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"
  vars_files:
    - ./inventories/group_vars/all.yml
  become: true
  roles:
    - postgresql
