---
- name: Install Docker
  hosts: app
  become: true
  roles:
    - docker
  vars:
    ansible_ssh_private_key_file: ".vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"
  vars_files:
    - ./inventories/group_vars/all.yml
  tasks:
    - name: Clone repository
      git:
        repo: "{{ repository_url }}"
        dest: /home/{{ ansible_user}}/{{ repository_dir }}
    - name: Start application from repository
      community.docker.docker_container:
        image: "{{ app_image }}"
        ports:
          - 8000:8000
        name: "{{ app_name }}"
        detach: true
        state: started

- name: Configure & start Nginx
  hosts: web
  become: true
  vars:
    ansible_ssh_private_key_file: ".vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"
    nginx__proxy_pass: http://192.168.56.201:8000
  vars_files:
    - ./inventories/group_vars/all.yml
  roles:
    - nginx