roles:
  - name: docker
    src: https://gitlab.com/ansible-roles5042950/docker.git
    scm: git
    version: master
  - name: nginx
    src: https://gitlab.com/ansible-roles5042950/nginx
    scm: git
    version: master